version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "biplav00"
    automerge: true
    automerge-method: "squash"
